twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        # the value is the service's id
        cart: '@App\Service\CartService'
when@test:
    twig:
        strict_variables: true
